# Generated by Django 5.2 on 2025-04-09 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organsharingapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='Logintable',
        ),
    ]
