# Generated by Django 5.2 on 2025-04-09 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organsharingapp', '0002_rename_login_logintable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientlist',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='organdonation',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='organdonation',
            name='hospital_name',
        ),
        migrations.RemoveField(
            model_name='organrequest',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='organrequest',
            name='hospital_name',
        ),
        migrations.RemoveField(
            model_name='organrequest',
            name='organ_type',
        ),
        migrations.AddField(
            model_name='organrequest',
            name='organ_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Organsharingapp.organdonation'),
        ),
        migrations.CreateModel(
            name='Usertable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('Login_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Organsharingapp.logintable')),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Organsharingapp.usertable'),
        ),
        migrations.AlterField(
            model_name='organdonation',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Organsharingapp.usertable'),
        ),
        migrations.AlterField(
            model_name='organrequest',
            name='patient_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Organsharingapp.usertable'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='PatientList',
        ),
    ]
