# Generated by Django 5.2 on 2025-04-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organsharingapp', '0004_organ_alter_organdonation_organ_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='age',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
