# Generated by Django 5.2 on 2025-04-10 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organsharingapp', '0006_usertable_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='organrequest',
            name='assigneddoctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Organsharingapp.doctor'),
        ),
        migrations.AddField(
            model_name='organrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
