# Generated by Django 5.2 on 2025-04-17 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organsharingapp', '0007_organrequest_assigneddoctor_organrequest_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='date',
            new_name='appointment_date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='time',
            new_name='appointment_time',
        ),
    ]
