# Generated by Django 5.2 on 2025-04-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organsharingapp', '0008_rename_date_appointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organdonation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='organdonation'),
        ),
    ]
