# Generated by Django 5.2 on 2025-04-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organsharingapp', '0009_organdonation_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='next_visit_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='prescriptions',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
