# Generated by Django 5.2 on 2025-04-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organsharingapp', '0010_appointment_next_visit_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organrequest',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='organrequest'),
        ),
        migrations.AddField(
            model_name='organrequest',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
