# Generated by Django 5.2 on 2025-04-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organsharingapp', '0011_organrequest_file_organrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organrequest',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=100, null=True),
        ),
    ]
