# Generated by Django 5.2 on 2025-04-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organsharingapp', '0015_alter_doctor_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='prescription_file',
            field=models.FileField(blank=True, null=True, upload_to='prescriptions'),
        ),
    ]
